### ISSUE TITLE
[RFE] Improvements to assist in using in systemd-units

### ISSUE THREAD

**Issue by TriMoon** [HoroTW/RazerBatteryTray#7] opened 2023-10-15 23:28 UTC
I have a few _"Requests For Enhancements"_ outlined below with separate headings...

---
## Only output detected devices with an option
Currently we only get a listing at the end of the output when run without any arguments.
It would be handy, especially for writing systemd units, to be able to have an option to only output detected devices one can use with this script :wink: 

fe. instead of:
```
Starting Razer Battery Tray
....
....
Listing Available Devices:
Razer Naga Pro (Wired)
    Has Battery: True
```
An output that can be easier parsed by scripts, eliminating any device without battery:
```
Razer Naga Pro (Wired)
```

## Allow the script to be silenced with an option
Currently it spams the logs with status updates, i had to silence it in the service unit i used.
_(I will post the units i use atm, which are still tobe considered W.I.P., at the bottom of this post)_

## Allow the script to exit cleanly when the device disappears.
At moment it seems it logs an exception with traceback but the process doesn't seem to be ended.
You can check self by using the units i use, and disconnect the device after showing the icon.

## Fix the script name in the example usage output
You should display the name the script was called with, especially when it was called using a symlink :wink: 
_(In my case i use a symlink named `razer-battery-icon`)_

Currently it shows:
```
Usage: razer_bat_tray.py <part_of_the_device_name>
Example 1: razer_bat_tray.py 'Razer Viper Ultimate'
Example 2: razer_bat_tray.py 'DeathAdder'
```
While the actual script in the repo is named 'razer_battery_tray.py` :rofl: 

---
Well so far for now... :wink: 

Below are the unit files i use:
1. They require the python script to be symlinked as `razer-battery-icon` under a path systemd-user service can find it, fe at `/usr/local/bin/razer-battery-icon`
1. The unit files below will show the name and location i placed them as.
   1. _(Optionally)_ "Enable" `razer-battery-icon.target` if you want the icon(s) to be started at login to the GUI.
   1. _(Optionally)_ "Enable" `razer-battery-icon.service` if you want the icon(s) for ALL razer devices to be started at login to the GUI.
_(This needs `razer-battery-icon.target` enabled)_
   1. _(Optionally)_ "Enable" `razer-battery-icon@<device name>.service` if you want the icon for a specific razer device to be started at login to the GUI.
_(This needs `razer-battery-icon.target` enabled)_
_(If you didn't enable `razer-battery-icon.service`, you can manually select which device icons to start by using these instance named ones instead.)_
1. You can start testing without enabling any unit by <kbd>systemctl --user start razer-battery-icon</kbd>, which will start the others automatically as needed.
You can then check which instances, with their proper names, were activated by using:
   ```console
   systemctl --user list-units 'razer-battery-icon@*'
   ```
   - To stop them all you can use <kbd>systemctl --user stop razer-battery-icon.target</kbd>
```ini
# ~/.config/systemd/user/razer-battery-icon.target
#	SPDX-License-Identifier: CC-BY-NC-SA-4.0
[Unit]
Description=%N: Autostart target
Documentation=https://wiki.archlinux.org/title/Systemd/User#Writing_user_units
Documentation=man:systemd.special(7)'#Units managed by the user service manage'
Documentation=man:systemd.unit(5)#Specifiers
Documentation=man:systemd.service(5)#Options
ConditionEnvironment=DISPLAY
ConditionEnvironment=XAUTHORITY
ConditionPathExistsGlob=/sys/bus/hid/drivers/razermouse/*/device_type
BindsTo=default.target

[Install]
WantedBy=xdg-desktop-autostart.target
```
```ini
# ~/.config/systemd/user/razer-battery-icon.service
#	SPDX-License-Identifier: CC-BY-NC-SA-4.0
[Unit]
Description=%N: Auto starter.
Documentation=https://wiki.archlinux.org/title/Systemd/User#Writing_user_units
Documentation=man:systemd.special(7)'#Units managed by the user service manage'
Documentation=man:systemd.unit(5)#Specifiers
Documentation=man:systemd.service(5)#Options
ConditionEnvironment=DISPLAY
ConditionEnvironment=XAUTHORITY
ConditionPathExistsGlob=/sys/bus/hid/drivers/razermouse/*/device_type
PartOf=razer-battery-icon.target
BindsTo=razer-battery-icon.target
Before=razer-battery-icon.target

[Service]
Type=exec
ExecStart=@bash '%N-Auto-starter' -c '\
	declare -A mice; \
	while true; do \
		mice=(); \
		for dev in /sys/bus/hid/drivers/razermouse/*/device_type; do \
			if test -s "$${dev}"; then \
				read -r mouse <$${dev}; \
				mice["$${mouse}"]=1; \
			fi; \
		done; \
		if test "$${#mice[@]}" -gt 0; then \
			for mouse in "$${!mice[@]}"; do \
				unitName="$$(systemd-escape --template=%N@.service "$${mouse}")"; \
				if systemctl --quiet --user is-failed "$${unitName}"; then \
					printf "%%s: %%s\n" \
						"Icon unit was failed for" \
						"$${mouse}"; \
					systemctl --user reset-failed "$${unitName}"; \
				fi; \
				if ! systemctl --quiet --user is-active "$${unitName}"; then \
					printf "%%s: %%s\n" \
						"starting icon unit for" \
						"$${mouse}"; \
					systemctl --no-block --user start "$${unitName}"; \
				fi; \
			done; \
		fi; \
		sleep 10; \
	done; \
'

[Install]
WantedBy=razer-battery-icon.target
```
```ini
# ~/.config/systemd/user/razer-battery-icon@.service
#	SPDX-License-Identifier: CC-BY-NC-SA-4.0
[Unit]
Description=%p: %I
Documentation=https://wiki.archlinux.org/title/Systemd/User#Writing_user_units
Documentation=man:systemd.special(7)'#Units managed by the user service manage'
Documentation=man:systemd.unit(5)#Specifiers
Documentation=man:systemd.service(5)#Options
PartOf=razer-battery-icon.target
BindsTo=razer-battery-icon.target
Before=razer-battery-icon.target

[Service]
Type=exec
StandardOutput=null
# ExecStart=%h/.local/bin/%p "%I"
ExecStart=%p "%I"
# ExecCondition=bash -rc '\
# 	for dev in /sys/bus/hid/drivers/razermouse/*/device_type; do \
# 		test "$$1" == "$$(cat $$dev)" && exit 0;\
# 	done;\
# 	exit 69\
# ' 'check_dev_name' "%I"
# Restart=on-failure
# RestartSec=5s

[Install]
WantedBy=razer-battery-icon.target
```

---
Hope these will be of help to you and anyone else reading :wink: 
Let me know if you need more explanation of the units i use, or any comments you may have...
:vulcan_salute:

**Comment by HoroTW** [comment] 2023-10-17 07:39
Hey there,
Thanks for the post, I basically agree with everything you said!

I'll keep you posted on the progress - probably tonight or tomorrow.

**Comment by HoroTW** [comment] 2023-10-19 04:36
Update:
I reworked the project to proof it for future extensions (also because it would now be too big for a single file with logging handling and better argument parsing).

What is already done:
- Only output detected devices with an option
  - There are now the `--list`, `--list-all` (all devices including those without battery) and `--parsable` (be less verbose) options.
    so using `razer-battery-icon --list --parsable` should give you the output:
    ```Razer Naga Pro (Wired/Wireless)```
- Script name in example usage output
  - Fixed, also the script (without arguments or with `--help') reflects the name of a symlink (if you use one)
- Allow the script to be silenced with an option
  - I added "proper" logging, so by default it shouldn't spam your logs anymore.
    You can now use the environment variable like this `LOG_LEVEL=DEBUG razer-battery-icon 'naga pro'`
    By default it uses the WARNING level 😉 .


What is not done yet:
- Update the `README.md` to reflect the new options
- Allow the script to cleanly exit when the device disappears. (will investigate that)
- Further testing

What do you think should be the correct behavior when the device disappears?
I would think that exiting the script is not really the ideal default behavior, but it should hide the icon and show it again when the device reappears.
Maybe a disconnected icon would also be an option... This handling would also require that the script be able to start with a device that is not currently connected.

What do you think?

I will push the changes to a separate branch and test it for a while (2-4 days).
I would appreciate it if you could test it as well.
If that's not possible, that's fine, but I'd like to increase the testing time a bit.

~Horo

**Comment by HoroTW** [comment] 2023-10-19 05:18
Okay I found the issue with the exception, nice catch! I had the script stopped working before but it was so rare that I didn't investigate! 😅

It's now capable of tolerating a device disconnecting and reconnecting. 😉
If the device is disconnected the tray icon gets hidden (moved into the overflow menu) and displays 0%.
After reconnect it gets shown again with the correct state. 😊

~Horo

**Comment by TriMoon** [comment] 2023-10-19 09:07
Sounds promising, ill test your changes as soon as you push the changes so i can pull them :wink:

**Comment by HoroTW** [comment] 2023-10-20 07:07
The changes are published in the branch [v.1.0](/HoroTW/RazerBatteryTray/tree/v.1.0)

**Comment by TriMoon** [comment] 2023-10-22 21:16
@HoroTW
I only started to test a few moments ago, looks good so far :+1: 
It just needs a `-h` as alias for `--help` :wink: 
Have not checked the debug functionality yet...

I need to re-coding my units for the changes also...

**Comment by TriMoon** [comment] 2023-10-23 19:05
@HoroTW , could you change the hover-over text to mention the devicename instead?
![image](https://github.com/HoroTW/RazerBatteryTray/assets/1723378/b6a23536-7286-4ac6-9c8b-c0bddb11950b)
Imagine multiple tray icons, when the user hovers over the icon it's better to show which device's charge is shown instead of the app name :wink:

**Comment by HoroTW** [comment] 2023-10-26 15:39
Hi @TriMoon,
Thank you very much for the feedback and your time!
I will now address the mentioned.

**Comment by HoroTW** [comment] 2023-10-26 15:48
- [x] Single dash options are added
- [ ] Cache for charge state while device is sleeping (that was previously a little much for the scope of the script but should now be addressable)
- [ ] Hover text - I will have to see what is possible, I wanted that back when I started... I added the device name to the context menu: 
![image](https://github.com/HoroTW/RazerBatteryTray/assets/8217773/6b3a9da3-ab67-4b9a-87ad-b8a51c6b8926)
- [ ] Exit app instead of waiting for reconnect - I see why you would like that behavior, I personally prefer it the other way around because it is much easier for the average joe to add a `razer-battery-icon viper` to their auto start and it just works. But I see the advantage to e.g. hook the device add, ..., so I will add it as an option

**Comment by HoroTW** [comment] 2023-10-26 17:45
Hey @TriMoon,
I'm done with the modifications, you can take a look if you want :)

**Comment by TriMoon** [comment] 2023-10-28 09:24
@HoroTW Thanks for the options, options are always good it makes it possible to use in different ways :wink: 
I will test the changes now :+1:

**Comment by HoroTW** [comment] 2023-11-07 14:56
Hey @TriMoon, how did the new version work out for you?
From my tests it works well and I have not noticed any regressions - what about you?

**Comment by TriMoon** [comment] 2023-11-07 16:57
@HoroTW 
It seems to work quite nice, i'm just in the progress of tweaking some stuff and adding the systemd units, i will post a PR when im done with them :wink:

**Comment by HoroTW** [comment] 2023-11-07 19:40
No problem! :)
Okay so I'm closing this now, looking forward to your pull request :+1:

**Closed by HoroTW** 2023-11-07 19:40 UTC
